# Generated by Django 4.1.3 on 2022-12-22 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Raw_ppg_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False, editable=False)),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Processed_ppg_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finished_time", models.DateTimeField(auto_now=True)),
                ("bpm", models.FloatField(blank=True, null=True)),
                ("ibi", models.FloatField(blank=True, null=True)),
                ("sdnn", models.FloatField(blank=True, null=True)),
                ("sdsd", models.FloatField(blank=True, null=True)),
                ("rmssd", models.FloatField(blank=True, null=True)),
                ("pnn20", models.FloatField(blank=True, null=True)),
                ("pnn50", models.FloatField(blank=True, null=True)),
                ("hr_mad", models.FloatField(blank=True, null=True)),
                ("sd1", models.FloatField(blank=True, null=True)),
                ("sd2", models.FloatField(blank=True, null=True)),
                ("s", models.FloatField(blank=True, null=True)),
                ("sd1sd2", models.FloatField(blank=True, null=True)),
                ("breathingrate", models.FloatField(blank=True, null=True)),
                ("vlf", models.FloatField(blank=True, null=True)),
                ("lf", models.FloatField(blank=True, null=True)),
                ("hf", models.FloatField(blank=True, null=True)),
                ("lfhf", models.FloatField(blank=True, null=True)),
                ("p_total", models.FloatField(blank=True, null=True)),
                ("vlf_perc", models.FloatField(blank=True, null=True)),
                ("hf_perc", models.FloatField(blank=True, null=True)),
                ("lf_nu", models.FloatField(blank=True, null=True)),
                ("hf_nu", models.FloatField(blank=True, null=True)),
                (
                    "raw_ppg_data_id",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ppg_analyser.raw_ppg_data",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppg_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"get_latest_by": "finished_time",},
        ),
    ]
