# Generated by Django 4.1.3 on 2023-01-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppg_analyser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="lfhf",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="pnn50",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="rmssd",
            field=models.FloatField(default=0),
        ),
    ]
