# Generated by Django 4.1.3 on 2022-12-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pageGenerator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ppg_data",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
