# Generated by Django 4.1.3 on 2022-12-12 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pageGenerator", "0002_alter_ppg_data_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Processed_ppg_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finished_time", models.DateTimeField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Raw_ppg_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="")),
                ("upload_time", models.DateTimeField()),
                ("processed", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="ppg_data",),
        migrations.AddField(
            model_name="processed_ppg_data",
            name="raw_ppg_data_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pageGenerator.raw_ppg_data",
            ),
        ),
    ]
