# Generated by Django 4.1.3 on 2022-12-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pageGenerator",
            "0003_processed_ppg_data_raw_ppg_data_delete_ppg_data_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="processed_ppg_data", old_name="person", new_name="user",
        ),
        migrations.RenameField(
            model_name="raw_ppg_data", old_name="person", new_name="user",
        ),
        migrations.AlterField(
            model_name="raw_ppg_data",
            name="upload_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
