# Generated by Django 4.1.3 on 2022-12-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pageGenerator", "0004_rename_person_processed_ppg_data_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="raw_ppg_data", old_name="upload_time", new_name="created",
        ),
    ]
