# Generated by Django 4.1.3 on 2022-12-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pageGenerator",
            "0006_alter_raw_ppg_data_processed_alter_raw_ppg_data_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cdsmodel",
            name="Please rate your cigarette addiction on a scale from 0 to 100 with 0 being not addicted and 100 being extremely addicted.",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cdsmodel",
            name="q2",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cdsmodel",
            name="q3",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
