# Generated by Django 4.1.3 on 2022-12-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pageGenerator",
            "0007_cdsmodel_please rate your cigarette addiction on a scale from 0 to 100 with 0 being not addicted and",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cdsmodel",
            name="Please rate your cigarette addiction on a scale from 0 to 100 with 0 being not addicted and 100 being extremely addicted.",
        ),
        migrations.RemoveField(model_name="cdsmodel", name="q2",),
        migrations.RemoveField(model_name="cdsmodel", name="q3",),
        migrations.AlterField(
            model_name="cdsmodel",
            name="score",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
