# Generated by Django 4.1.3 on 2022-12-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pageGenerator",
            "0009_cdsmodel_q1_cdsmodel_q10_cdsmodel_q11_cdsmodel_q12_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cdsmodel",
            name="q4",
            field=models.CharField(
                choices=[
                    (1, "Impossible"),
                    (2, "Very difficult"),
                    (3, "Fairly difficult"),
                    (4, "Fairly easy"),
                    (5, "Very easy"),
                ],
                max_length=20,
                null=True,
                verbose_name="For you, quitting smoking for good would be:",
            ),
        ),
    ]
