# Generated by Django 4.1.3 on 2022-12-12 17:28

from django.db import migrations, models
import pageGenerator.models


class Migration(migrations.Migration):

    dependencies = [
        ("pageGenerator", "0010_alter_cdsmodel_q4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cdsmodel",
            name="q1",
            field=models.IntegerField(
                validators=[pageGenerator.models.CDSModel.validate_between_0_100],
                verbose_name="Please rate your cigarette addiction on a scale from 0 to 100 with 0 being not addicted and 100 being extremely addicted.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q10",
            field=models.CharField(
                choices=[
                    (1, "Totally disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree nor disagree"),
                    (4, "Somewhat agree"),
                    (5, "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="Sometimes I drop everything to go out and buy cigarettes",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q11",
            field=models.CharField(
                choices=[
                    (1, "Totally disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree nor disagree"),
                    (4, "Somewhat agree"),
                    (5, "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I smoke all the time.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q12",
            field=models.CharField(
                choices=[
                    (1, "Totally disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree nor disagree"),
                    (4, "Somewhat agree"),
                    (5, "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I smoke despite the risks to my health",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q2",
            field=models.IntegerField(
                validators=[pageGenerator.models.CDSModel.validate_between_0_100],
                verbose_name="On average, how many cigarettes do you smoke per day?",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q3",
            field=models.IntegerField(
                validators=[pageGenerator.models.CDSModel.validate_between_0_100],
                verbose_name="How soon after waking up do you smoke your first cigarette?",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q4",
            field=models.CharField(
                choices=[
                    (1, "Impossible"),
                    (2, "Very difficult"),
                    (3, "Fairly difficult"),
                    (4, "Fairly easy"),
                    (5, "Very easy"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="For you, quitting smoking for good would be:",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q5",
            field=models.CharField(
                choices=[
                    (1, "Totally disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree nor disagree"),
                    (4, "Somewhat agree"),
                    (5, "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="After a few hours without smoking, I feel an irresistable urge to smoke.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q6",
            field=models.CharField(
                choices=[
                    (1, "Totally disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree nor disagree"),
                    (4, "Somewhat agree"),
                    (5, "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="The idea of not having any cigarettes causes me stress.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q7",
            field=models.CharField(
                choices=[
                    (1, "Totally disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree nor disagree"),
                    (4, "Somewhat agree"),
                    (5, "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="Before going out, I always make sure that I have cigarettes with me.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q8",
            field=models.CharField(
                choices=[
                    (1, "Totally disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree nor disagree"),
                    (4, "Somewhat agree"),
                    (5, "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I am a prisoner of cigarettes.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q9",
            field=models.CharField(
                choices=[
                    (1, "Totally disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree nor disagree"),
                    (4, "Somewhat agree"),
                    (5, "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I smoke too much.",
            ),
        ),
    ]
