# Generated by Django 4.1.3 on 2022-12-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pageGenerator", "0012_alter_cdsmodel_q1_alter_cdsmodel_q2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adsmodel",
            name="q1",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes sometimes"), ("2", "Yes, usually")],
                default=None,
                max_length=50,
                verbose_name="Do you get belligerent or mean when you drink?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q10",
            field=models.CharField(
                choices=[("0", "Yes"), ("1", "No")],
                default=None,
                max_length=50,
                verbose_name="Do you sneak drinks or hide bottles?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q11",
            field=models.CharField(
                choices=[("0", "Yes"), ("1", "No")],
                default=None,
                max_length=50,
                verbose_name="Do you lose control over what you do when you are drinking? ",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q12",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes, once"), ("2", "Yes, several times")],
                default=None,
                max_length=50,
                verbose_name="As a result of drinking, have you seen things that were not there?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q13",
            field=models.CharField(
                choices=[
                    ("0", "No"),
                    ("1", "Yes sometimes"),
                    ("2", "Yes, almost every time I drink"),
                ],
                default=None,
                max_length=50,
                verbose_name='Have you had "shakes" when sobering up (hands tremble, shake inside, etc.) as a result of drinking?',
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q14",
            field=models.CharField(
                choices=[("0", "Yes"), ("1", "No")],
                default=None,
                max_length=50,
                verbose_name="Do you usually have a bottle by your bedside?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q15",
            field=models.CharField(
                choices=[("0", "Yes"), ("1", "No")],
                default=None,
                max_length=50,
                verbose_name="Do you drink throughout the day?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q16",
            field=models.CharField(
                choices=[
                    ("0", "Have never had a blackout"),
                    ("1", "Have had blackouts that last less than an hour"),
                    ("2", "Have had blackouts that last for several hours"),
                    (4, "Have had blackouts that last for a day or more"),
                ],
                default=None,
                max_length=50,
                verbose_name="With respect to blackouts (loss of memory):",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q17",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes once"), ("2", "Yes, sereval times")],
                default=None,
                max_length=50,
                verbose_name='As a result of drinking have you heard "things" that were not there?',
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q18",
            field=models.CharField(
                choices=[("0", "Yes"), ("1", "No")],
                default=None,
                max_length=50,
                verbose_name="Do you often have hangovers on Sunday or Monday mornings?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q19",
            field=models.CharField(
                choices=[("0", "Yes"), ("1", "No")],
                default=None,
                max_length=50,
                verbose_name="Do you almost constantly think about drinking and alcohol?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q2",
            field=models.CharField(
                choices=[
                    ("0", "No, never"),
                    ("1", "Sometimes"),
                    ("2", "Often"),
                    ("3", "Almost every time I drink"),
                ],
                default=None,
                max_length=50,
                verbose_name='Have you had blackouts ("loss of memory" without passing out) as a result of drinking?',
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q20",
            field=models.CharField(
                choices=[("0", "Yes"), ("1", "No")],
                default=None,
                max_length=50,
                verbose_name="Do you tend to be physically harmful to other people when drinking?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q21",
            field=models.CharField(
                choices=[
                    ("0", "No"),
                    ("1", "Yes, perhaps once or twice"),
                    ("2", "Yes, often"),
                ],
                default=None,
                max_length=50,
                verbose_name="Have you had weird and frightening sensations when drinking?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q22",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Once"), ("2", "Several times")],
                default=None,
                max_length=50,
                verbose_name='As a result of drinking have you "felt things" crawling on you that were not there (bugs, spiders, etc.)?',
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q23",
            field=models.CharField(
                choices=[
                    ("0", "No"),
                    ("1", "Sometimes"),
                    ("2", "Almost every time I drink"),
                ],
                default=None,
                max_length=50,
                verbose_name="Do you get physically sick (vomit, stomach cramps, etc.) as a result of drinking?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q24",
            field=models.CharField(
                choices=[
                    ("0", "No"),
                    ("1", "Some of the time"),
                    ("2", "Most of the time"),
                ],
                default=None,
                max_length=50,
                verbose_name="Do you carry a bottle with you or keep one close at hand?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q25",
            field=models.CharField(
                choices=[("0", "Never"), ("1", "Once"), ("2", "Several times")],
                default=None,
                max_length=50,
                verbose_name="Have you ever attempted suicide when drinking?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q26",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes, once"), ("2", "Several times")],
                default=None,
                max_length=50,
                verbose_name="As a result of drinking, have you ever had delirium tremens or DT's (seen, felt, or heard things not really there)?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q27",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes, once"), ("2", "Yes, several times")],
                default=None,
                max_length=50,
                verbose_name="As a result of drinking have you felt your heart beating rapidly?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q28",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes, once"), ("2", "Yes, several times")],
                default=None,
                max_length=50,
                verbose_name="As a result of drinking have you felt overly hot and sweaty (feverish)?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q29",
            field=models.CharField(
                choices=[("0", "Yes"), ("1", "No")],
                default=None,
                max_length=50,
                verbose_name="Do you drink during your work day?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q3",
            field=models.CharField(
                choices=[
                    ("0", "Enough to get high or less"),
                    ("1", "Enough to get drunk"),
                    ("2", "Enough to pass out"),
                ],
                default=None,
                max_length=50,
                verbose_name="How much did you drink the last time you drank?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q4",
            field=models.CharField(
                choices=[
                    ("0", "No"),
                    ("1", "About once a year"),
                    ("2", "Twice a year or more"),
                ],
                default=None,
                max_length=50,
                verbose_name="Have you passed out as a result of drinking?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q5",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Sometimes"), ("2", "Often")],
                default=None,
                max_length=50,
                verbose_name="When you drink, do you stumble about, stagger and weave?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q6",
            field=models.CharField(
                choices=[("0", "Yes"), ("1", "No")],
                default=None,
                max_length=50,
                verbose_name="Do you gulp drinks (drink quickly)?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q7",
            field=models.CharField(
                choices=[
                    ("0", "No"),
                    ("1", "Yes, but only for a few hours"),
                    ("2", "Yes, for one or two days"),
                    (4, "Yes, for many days"),
                ],
                default=None,
                max_length=50,
                verbose_name="As a result of being drunk, has your thinking been fuzzy or unclear?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q8",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Once"), ("2", "Several times")],
                default=None,
                max_length=50,
                verbose_name="Have you had a convulsion (fit) following a period of drinking?",
            ),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="q9",
            field=models.CharField(
                choices=[("0", "Yes"), ("1", "No")],
                default=None,
                max_length=50,
                verbose_name="Do you panic because you fear you may not have a drink when you need it?",
            ),
        ),
        migrations.AlterField(
            model_name="adsmodel",
            name="score",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q10",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="Sometimes I drop everything to go out and buy cigarettes",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q11",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I smoke all the time.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q12",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I smoke despite the risks to my health",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q4",
            field=models.CharField(
                choices=[
                    ("1", "Impossible"),
                    ("2", "Very difficult"),
                    ("3", "Fairly difficult"),
                    ("4", "Fairly easy"),
                    ("5", "Very easy"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="For you, quitting smoking for good would be:",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q5",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="After a few hours without smoking, I feel an irresistable urge to smoke.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q6",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="The idea of not having any cigarettes causes me stress.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q7",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="Before going out, I always make sure that I have cigarettes with me.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q8",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I am a prisoner of cigarettes.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q9",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I smoke too much.",
            ),
        ),
    ]
