# Generated by Django 4.1.3 on 2022-12-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pageGenerator",
            "0013_adsmodel_q1_adsmodel_q10_adsmodel_q11_adsmodel_q12_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsmodel",
            name="q16",
            field=models.CharField(
                choices=[
                    ("0", "Have never had a blackout"),
                    ("1", "Have had blackouts that last less than an hour"),
                    ("2", "Have had blackouts that last for several hours"),
                    ("3", "Have had blackouts that last for a day or more"),
                ],
                default=None,
                max_length=50,
                verbose_name="With respect to blackouts (loss of memory):",
            ),
        ),
        migrations.AlterField(
            model_name="adsmodel",
            name="q7",
            field=models.CharField(
                choices=[
                    ("0", "No"),
                    ("1", "Yes, but only for a few hours"),
                    ("2", "Yes, for one or two days"),
                    ("3", "Yes, for many days"),
                ],
                default=None,
                max_length=50,
                verbose_name="As a result of being drunk, has your thinking been fuzzy or unclear?",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q10",
            field=models.CharField(
                choices=[
                    ("0", "Totally disagree"),
                    ("1", "Somewhat disagree"),
                    ("2", "Neither agree nor disagree"),
                    ("3", "Somewhat agree"),
                    ("4", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="Sometimes I drop everything to go out and buy cigarettes",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q11",
            field=models.CharField(
                choices=[
                    ("0", "Totally disagree"),
                    ("1", "Somewhat disagree"),
                    ("2", "Neither agree nor disagree"),
                    ("3", "Somewhat agree"),
                    ("4", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I smoke all the time.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q12",
            field=models.CharField(
                choices=[
                    ("0", "Totally disagree"),
                    ("1", "Somewhat disagree"),
                    ("2", "Neither agree nor disagree"),
                    ("3", "Somewhat agree"),
                    ("4", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I smoke despite the risks to my health",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q5",
            field=models.CharField(
                choices=[
                    ("0", "Totally disagree"),
                    ("1", "Somewhat disagree"),
                    ("2", "Neither agree nor disagree"),
                    ("3", "Somewhat agree"),
                    ("4", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="After a few hours without smoking, I feel an irresistable urge to smoke.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q6",
            field=models.CharField(
                choices=[
                    ("0", "Totally disagree"),
                    ("1", "Somewhat disagree"),
                    ("2", "Neither agree nor disagree"),
                    ("3", "Somewhat agree"),
                    ("4", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="The idea of not having any cigarettes causes me stress.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q7",
            field=models.CharField(
                choices=[
                    ("0", "Totally disagree"),
                    ("1", "Somewhat disagree"),
                    ("2", "Neither agree nor disagree"),
                    ("3", "Somewhat agree"),
                    ("4", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="Before going out, I always make sure that I have cigarettes with me.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q8",
            field=models.CharField(
                choices=[
                    ("0", "Totally disagree"),
                    ("1", "Somewhat disagree"),
                    ("2", "Neither agree nor disagree"),
                    ("3", "Somewhat agree"),
                    ("4", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I am a prisoner of cigarettes.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q9",
            field=models.CharField(
                choices=[
                    ("0", "Totally disagree"),
                    ("1", "Somewhat disagree"),
                    ("2", "Neither agree nor disagree"),
                    ("3", "Somewhat agree"),
                    ("4", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I smoke too much.",
            ),
        ),
    ]
