# Generated by Django 4.1.3 on 2022-12-13 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pageGenerator", "0017_alter_adsmodel_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adsmodel", options={"get_latest_by": "created"},
        ),
        migrations.AlterModelOptions(
            name="cdsmodel", options={"get_latest_by": "created"},
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
