# Generated by Django 4.1.3 on 2022-12-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pageGenerator", "0020_alter_scoremodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoremodel",
            name="value",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
