# Generated by Django 4.1.3 on 2022-12-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pageGenerator", "0022_processed_ppg_data_bpm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="bpm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="breathingrate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="hf",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="hf_nu",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="hf_perc",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="hr_mad",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="ibi",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="lf",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="lf_nu",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="lfhf",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="p_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="pnn20",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="pnn50",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="rmssd",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="s",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="sd1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="sd1sd2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="sd2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="sdnn",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="sdsd",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="vlf",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="vlf_perc",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
