# Generated by Django 4.1.3 on 2022-12-19 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pageGenerator", "0023_alter_processed_ppg_data_bpm_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processed_ppg_data", options={"get_latest_by": "finished_time"},
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="raw_ppg_data_id",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="pageGenerator.raw_ppg_data",
            ),
        ),
        migrations.AlterField(
            model_name="processed_ppg_data",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ppg_data",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="BMIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("height", models.FloatField(verbose_name="height")),
                ("mass", models.FloatField(verbose_name="weight")),
                ("bmi", models.FloatField(editable=False)),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bmi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"get_latest_by": "created",},
        ),
    ]
