# Generated by Django 4.1.3 on 2023-01-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifestyleforms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsmodel",
            name="q10",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")],
                default=None,
                max_length=50,
                verbose_name="Do you sneak drinks or hide bottles?",
            ),
        ),
        migrations.AlterField(
            model_name="adsmodel",
            name="q11",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")],
                default=None,
                max_length=50,
                verbose_name="Do you lose control over what you do when you are drinking? ",
            ),
        ),
        migrations.AlterField(
            model_name="adsmodel",
            name="q14",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")],
                default=None,
                max_length=50,
                verbose_name="Do you usually have a bottle by your bedside?",
            ),
        ),
        migrations.AlterField(
            model_name="adsmodel",
            name="q15",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")],
                default=None,
                max_length=50,
                verbose_name="Do you drink throughout the day?",
            ),
        ),
        migrations.AlterField(
            model_name="adsmodel",
            name="q18",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")],
                default=None,
                max_length=50,
                verbose_name="Do you often have hangovers on Sunday or Monday mornings?",
            ),
        ),
        migrations.AlterField(
            model_name="adsmodel",
            name="q19",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")],
                default=None,
                max_length=50,
                verbose_name="Do you almost constantly think about drinking and alcohol?",
            ),
        ),
        migrations.AlterField(
            model_name="adsmodel",
            name="q20",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")],
                default=None,
                max_length=50,
                verbose_name="Do you tend to be physically harmful to other people when drinking?",
            ),
        ),
        migrations.AlterField(
            model_name="adsmodel",
            name="q29",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")],
                default=None,
                max_length=50,
                verbose_name="Do you drink during your work day?",
            ),
        ),
        migrations.AlterField(
            model_name="adsmodel",
            name="q6",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")],
                default=None,
                max_length=50,
                verbose_name="Do you gulp drinks (drink quickly)?",
            ),
        ),
        migrations.AlterField(
            model_name="adsmodel",
            name="q9",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")],
                default=None,
                max_length=50,
                verbose_name="Do you panic because you fear you may not have a drink when you need it?",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q10",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="Sometimes I drop everything to go out and buy cigarettes",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q11",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I smoke all the time.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q12",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I smoke despite the risks to my health",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q4",
            field=models.CharField(
                choices=[
                    ("5", "Impossible"),
                    ("4", "Very difficult"),
                    ("3", "Fairly difficult"),
                    ("2", "Fairly easy"),
                    ("1", "Very easy"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="For you, quitting smoking for good would be:",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q5",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="After a few hours without smoking, I feel an irresistable urge to smoke.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q6",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="The idea of not having any cigarettes causes me stress.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q7",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="Before going out, I always make sure that I have cigarettes with me.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q8",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I am a prisoner of cigarettes.",
            ),
        ),
        migrations.AlterField(
            model_name="cdsmodel",
            name="q9",
            field=models.CharField(
                choices=[
                    ("1", "Totally disagree"),
                    ("2", "Somewhat disagree"),
                    ("3", "Neither agree nor disagree"),
                    ("4", "Somewhat agree"),
                    ("5", "Fully agree"),
                ],
                default=None,
                max_length=20,
                verbose_name="I smoke too much.",
            ),
        ),
    ]
